# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 646233cb3d77ebbeb27b14f79cace89e61c04ec3b2170573108c3a3e74717111d29ad8601fc7f50b24ed3383ff675400b1e749aa8d6494759c810922e6de9baa

test:
  secret_key_base: f5311bc902082fb1b71a8ff6486c2fc8306b2da3cbe77880ad6335bb505b44a95ec3e22e71129fa35c119a7a348c282d9071ce6a81cdd41d38f6b8db9ebc9652

qa:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

uat:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
